// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_MG1pEtmHMtqnwYgmour7L3S1dKaJklU',
    appId: '1:1460615228:web:fd8d4261bacfcd697d6b39',
    messagingSenderId: '1460615228',
    projectId: 'car-rental-system-e97dd',
    authDomain: 'car-rental-system-e97dd.firebaseapp.com',
    storageBucket: 'car-rental-system-e97dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY7wn-H6lTJXbuJ8gWC0VFVYgDgG1K1us',
    appId: '1:1460615228:android:4ecddf3a613fd2627d6b39',
    messagingSenderId: '1460615228',
    projectId: 'car-rental-system-e97dd',
    storageBucket: 'car-rental-system-e97dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjzwgY1EJLzTQ_1Td7VelI4F1bjKQsC60',
    appId: '1:1460615228:ios:16fc441e72ede38c7d6b39',
    messagingSenderId: '1460615228',
    projectId: 'car-rental-system-e97dd',
    storageBucket: 'car-rental-system-e97dd.firebasestorage.app',
    iosBundleId: 'com.carrentalsystem.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjzwgY1EJLzTQ_1Td7VelI4F1bjKQsC60',
    appId: '1:1460615228:ios:2c37ddf4087c1eaf7d6b39',
    messagingSenderId: '1460615228',
    projectId: 'car-rental-system-e97dd',
    storageBucket: 'car-rental-system-e97dd.firebasestorage.app',
    iosBundleId: 'com.example.carRentalSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_MG1pEtmHMtqnwYgmour7L3S1dKaJklU',
    appId: '1:1460615228:web:3094e412c7d110127d6b39',
    messagingSenderId: '1460615228',
    projectId: 'car-rental-system-e97dd',
    authDomain: 'car-rental-system-e97dd.firebaseapp.com',
    storageBucket: 'car-rental-system-e97dd.firebasestorage.app',
  );
}
